name: Auto-assign issues and pull requests

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign issue
        if: github.event_name == 'issues'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: SammeLn1719
          label: 'triage'

      - name: Auto-assign pull request
        if: github.event_name == 'pull_request'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: SammeLn1719
          label: 'review'
