name: Comment on issues and pull requests

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for opening an issue!

Please make sure you've:
- [ ] Checked the [troubleshooting guide](https://github.com/${context.repo.owner}/${context.repo.repo}#troubleshooting)
- [ ] Searched existing [issues](https://github.com/${context.repo.owner}/${context.repo.repo}/issues) for similar problems
- [ ] Provided detailed information about your environment and the issue

We'll review your issue and get back to you soon! 🚀`
            })

      - name: Comment on pull request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎉 Thanks for your pull request!

Please make sure you've:
- [ ] Tested in multiple browsers (Chrome, Firefox, Edge)
- [ ] Verified the extension functionality works as expected
- [ ] Followed the [contributing guidelines](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/CONTRIBUTING.md)

We'll review your changes and provide feedback soon! 🚀`
            })
