name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        fi

    - name: Build Chrome extension
      run: |
        if [ -f build.sh ]; then
          chmod +x build.sh
          ./build.sh
        fi

    - name: Build Firefox extension
      run: |
        if [ -f build-firefox.sh ]; then
          chmod +x build-firefox.sh
          ./build-firefox.sh
        fi

    - name: Create release assets
      run: |
        # Create Chrome extension zip
        if [ -d build ]; then
          cd build
          zip -r ../youtube-shorts-blocker-chrome-v${GITHUB_REF#refs/tags/}.zip .
          cd ..
        fi
        
        # Create Firefox extension zip
        if [ -d build-firefox ]; then
          cd build-firefox
          zip -r ../youtube-shorts-blocker-firefox-v${GITHUB_REF#refs/tags/}.zip .
          cd ..
        fi

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## 🎉 Release ${{ github.ref }}
          
          ### 📦 Installation
          
          #### Chrome/Edge
          1. Download the Chrome extension zip file
          2. Extract the files
          3. Go to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked extension"
          6. Select the extracted folder
          
          #### Firefox
          1. Download the Firefox extension zip file
          2. Extract the files
          3. Go to `about:debugging`
          4. Click "This Firefox"
          5. Click "Load Temporary Add-on"
          6. Select `manifest.json` from the extracted folder
          
          ### 📋 Changelog
          See [CHANGELOG.md](CHANGELOG.md) for detailed information.
          
          ### 🤝 Contributing
          Thank you to all contributors who helped with this release!
          
          ### 📞 Support
          If you encounter any issues, please:
          1. Check the [troubleshooting guide](README.md#troubleshooting)
          2. Search existing [issues](../../issues)
          3. Create a new issue with detailed information
          
          ---
          
          **Enjoy a more productive YouTube experience!** 🚀
        draft: false
        prerelease: false

    - name: Upload Chrome Extension
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./youtube-shorts-blocker-chrome-v${{ github.ref_name }}.zip
        asset_name: youtube-shorts-blocker-chrome-v${{ github.ref_name }}.zip
        asset_content_type: application/zip

    - name: Upload Firefox Extension
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./youtube-shorts-blocker-firefox-v${{ github.ref_name }}.zip
        asset_name: youtube-shorts-blocker-firefox-v${{ github.ref_name }}.zip
        asset_content_type: application/zip
