name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          days-before-stale: 90
          days-before-close: 7
          exempt-issue-labels: 'pinned,security,good first issue,help wanted'
          exempt-pr-labels: 'pinned,security'
          exempt-all-milestones: true
          exempt-all-assignees: true
          exempt-all-issue-assignees: true
          exempt-all-pr-assignees: true
